spring.application.name=batalhanaval

# Actuator

management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:batalhanaval-not-that-secret}
jwt.expiration-hours=1