spring.application.name=batalhanaval

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/batalhanaval
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:batalhanaval-not-that-secret}
jwt.expiration-hours=1